services:
  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk-network

  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
        LOGSTASH_INTERNAL_PASSWORD: $LOGSTASH_INTERNAL_PASSWORD
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5001:5000"
      - "5044:5044"
    networks:
      - elk-network
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./kibana
      dockerfile: Dockerfile
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
        ELASTIC_PASSWORD: $ELASTIC_PASSWORD
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk-network
    depends_on:
      - elasticsearch

networks:
  elk-network:
    driver: bridge

volumes:
  elasticsearch-data:
